# Generated by Django 2.1.3 on 2018-11-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181102_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='uer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='comment',
            field=models.CharField(default='', max_length=256, verbose_name='商品评论'),
        ),
    ]
